apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
      - name: xxx
        image: xxx
        ports:
        - containerPort: xxx
        env:
        - name: ENV_VAR_1_NAME
          value: "ENV_VAR_1_VALUE"
        livenessProbe:
          periodSeconds: x
          exec: 
            command: ["xxx-exec-command", "xxx-args"]
        readinessProbe:
          periodSeconds: x
          exec: 
            command: ["xxx-exec-command", "xxx-args"]
        resources:
          requests:
            cpu: 100m   
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
